### ISSUE TITLE
Can't adjust build % of turrets

### ISSUE THREAD

**Issue by AnonymousMonkey75** [SEModCommunity/SE-Community-Mod-API#160]
If you try it crashes after a few second. Repeated three times.

2014-09-14 21:02:20.247 - Thread: 9 -> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Weapons.MyLargeTurretBase.UpdateAfterSimulation()
   at Sandbox.Game.Weapons.MyLargeMissileTurret.UpdateAfterSimulation()
   at 5BCAC68007431E61367F5B2CF24E2D6F.CAF1EB435F77C7B77580E2E16F988BED.C6A5F4D30318F3005DC853C9269C7358()
   at AAC05F537A6F0F6775339593FBDFC564.CBB94D06E8011132FF514442B0A88989.UpdateAfterSimulation()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.F672BBF9E192151CE8FD7E91E62B997D()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.EC90B1C44E3C361983D093F355FF0CC8(Single D0A668B86020514B76C774AD3D4C5778)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.10BFA1A6DF29D72FD55E84B0A99C00BC()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.2457E95BE2F0D1F1A4A009B2B1DBBDA4()
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.858DA51EB20785A82D9A03614304088A.0187A29A24275EC024A192E7E235CC2E.9C41E76459B99591F991CBA0833BD17E()
   at 168638249D29224100DB50BB468E7C07.6E0E814918D8AD6B2DC9CA5005102256.C2F01375F41D7385253E752B5AE8C4DD(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.C2F01375F41D7385253E752B5AE8C4DD(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.246E732EE67F7F6F88C4FF63B3901107(Boolean FF8E4184144DE7049FF5EC07D594DAB6)
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.523C8831DA5DAB3A19F6D33A2C6437B5()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.26A7ABEA729FAE1F24679E21470F8E98(String 8BF03A34188889479CB413E58490FC37, String 48C45E39212AAA2B19C972DA9195F48A, Boolean 7AC487C1B445CD9F481CF5FE695A7CEA, Boolean 4292A7A4DACAF323E558B7E11DD3CF00)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.Server.ServerAssemblyWrapper.StartServer(String instanceName, String overridePath, Boolean useConsole)
2014-09-14 21:02:20.247 - Thread: 9 -> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Weapons.MyLargeTurretBase.UpdateAfterSimulation()
   at Sandbox.Game.Weapons.MyLargeMissileTurret.UpdateAfterSimulation()
   at 5BCAC68007431E61367F5B2CF24E2D6F.CAF1EB435F77C7B77580E2E16F988BED.C6A5F4D30318F3005DC853C9269C7358()
   at AAC05F537A6F0F6775339593FBDFC564.CBB94D06E8011132FF514442B0A88989.UpdateAfterSimulation()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.F672BBF9E192151CE8FD7E91E62B997D()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.EC90B1C44E3C361983D093F355FF0CC8(Single D0A668B86020514B76C774AD3D4C5778)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.10BFA1A6DF29D72FD55E84B0A99C00BC()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.2457E95BE2F0D1F1A4A009B2B1DBBDA4()
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.858DA51EB20785A82D9A03614304088A.0187A29A24275EC024A192E7E235CC2E.9C41E76459B99591F991CBA0833BD17E()
   at 168638249D29224100DB50BB468E7C07.6E0E814918D8AD6B2DC9CA5005102256.C2F01375F41D7385253E752B5AE8C4DD(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at 168638249D29224100DB50BB468E7C07.398AD1E315E6E4D570C424BD0D168FC1.C2F01375F41D7385253E752B5AE8C4DD(9AA159E6C22F64A542015EED199D04B9 148A5BA193EB90E55F5E805EF96CAD48)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.246E732EE67F7F6F88C4FF63B3901107(Boolean FF8E4184144DE7049FF5EC07D594DAB6)
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.523C8831DA5DAB3A19F6D33A2C6437B5()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.26A7ABEA729FAE1F24679E21470F8E98(String 8BF03A34188889479CB413E58490FC37, String 48C45E39212AAA2B19C972DA9195F48A, Boolean 7AC487C1B445CD9F481CF5FE695A7CEA, Boolean 4292A7A4DACAF323E558B7E11DD3CF00)
2014-09-14 21:02:20.263 - Thread: 9 ->    at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at SEModAPIInternal.API.Server.ServerAssemblyWrapper.StartServer(String instanceName, String overridePath, Boolean useConsole)
   at SEModAPIExtensions.API.Server.RunServer()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2014-09-14 21:02:20.279 - Thread: 9 -> Unloading plugin '774c4148-1da1-4ee0-b7f0-eb51ca296e9b'
2014-09-14 21:02:20.310 - Thread: 9 -> Shutting down Blueprints Plugin
2014-09-14 21:02:20.310 - Thread: 9 -> Unloading plugin 'f625a48b-c28c-4ba4-a39a-637824614d0f'
2014-09-14 21:02:20.419 - Thread: 20 -> Blueprints Processing Thread Closed: System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.SleepInternal(Int32 millisecondsTimeout)
   at System.Threading.Thread.Sleep(Int32 millisecondsTimeout)
   at BlueprintsPlugin.BlueprintsPlugin.BlueprintsThreadWork()

**Comment by Tyrsis** [comment]
Yes this is a known issue.  If you spawn a ship that has turrets or grinders, and then set their %, it will crash the game.  It's an in game bug sadly, and not part of the API.  I had to get around this in the blueprints mod by just setting them to 100% built when I spawn the blueprint.

**Comment by AnonymousMonkey75** [comment]
I just got that error again, exact same, this time local side. Was just flying around. Three other people got CTDed at same time.

**Comment by Tyrsis** [comment]
Yes, this will crash everyone on the server, including the server.

**Comment by AnonymousMonkey75** [comment]
Sometimes it does not crash the server. I have also had a problem lately with turrets just disappearing. And now I'm wondering if maybe only occurring on the imported cube grids....because not all of them are doing it.

**Comment by Tyrsis** [comment]
Yeah, it is a weird one.  It is listed under bug #118 already though.  This is the same thing.  I'm not entirely sure if it's an extender bug, but more of the game not liking turrets / large grinders being built by anything other than a welder.

**Comment by fvgoulet** [comment]
We need to be sure of what causes it and if there is any clean workaround
