### ISSUE TITLE
Unable to launch SE Server Extender for First time

### ISSUE THREAD

**Issue by mrgoo** [SEModCommunity/SE-Community-Mod-API#184]
OS is Win Server 2008 R2
Dot Net 4.0 + Is Installed.
The dedicated server run as console and service mode both no issue (vanilla no extender)
When i attempt to launch the extender I get the following error

I can not find a log file in fact error is in api log creation see output below.

PS C:\Steam\se\DedicatedServer64> .\SEServerExtender.exe
Finished loading LogManager
Finished loading SandboxGameAssemblyWrapper
System.TypeLoadException: Could not load type 'Sandbox.Definitions.MyDefinitionId' from assembly 'Sa
ndbox.Game, Version=0.1.5522.32807, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.get_IsGameStarted()
   at SEModAPIInternal.Support.ApplicationLog..ctor(Boolean useGamePath)
   at SEModAPIInternal.Support.LogManager.get_APILog()
AppDomain.UnhandledException - System.Exception: Failed to create API log!
   at SEModAPIInternal.Support.LogManager.get_APILog()
   at SEServerExtender.Program.Start(String[] args)
   at SEServerExtender.Program.Main(String[] args)
System.TypeLoadException: Could not load type 'Sandbox.Definitions.MyDefinitionId' from assembly 'Sa
ndbox.Game, Version=0.1.5522.32807, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.API.Common.SandboxGameAssemblyWrapper.get_IsGameStarted()
   at SEModAPIInternal.Support.ApplicationLog..ctor(Boolean useGamePath)
   at SEModAPIInternal.Support.LogManager.get_APILog()

Unhandled Exception: System.Exception: Failed to create API log!
   at SEModAPIInternal.Support.LogManager.get_APILog()
   at SEServerExtender.Program.Start(String[] args)
   at SEServerExtender.Program.Main(String[] args)
PS C:\Steam\se\DedicatedServer64>

Ran the Exe by click and then when the window crashes and does not stay open I launched it from Power Shell so I could provide more details.

**Comment by pveeckhout** [comment]
I have a similar problem, the SEServerExtender fails to launch.

OS Win8.1 x64

```
Finished loading LogManager
System.TypeLoadException: Could not load type 'VRage.Common.Utils.MyFileSystem'
from assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=n
ull'.
   at SEModAPIInternal.Support.ApplicationLog..ctor(Boolean useGamePath)
   at SEModAPIInternal.Support.LogManager.get_APILog()
AppDomain.UnhandledException - System.Exception: Failed to create API log!
   at SEModAPIInternal.Support.LogManager.get_APILog()
   at SEServerExtender.Program.Start(String[] args)
   at SEServerExtender.Program.Main(String[] args)
System.TypeLoadException: Could not load type 'VRage.Common.Utils.MyFileSystem'
from assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=n
ull'.
   at SEModAPIInternal.Support.ApplicationLog..ctor(Boolean useGamePath)
   at SEModAPIInternal.Support.LogManager.get_APILog()

Unhandled Exception: System.Exception: Failed to create API log!
   at SEModAPIInternal.Support.LogManager.get_APILog()
   at SEServerExtender.Program.Start(String[] args)
   at SEServerExtender.Program.Main(String[] args)
```

**Comment by JohanSpannare** [comment]
Referenced assemblies are missing:
It exists two diffrent versions of VRage.Library with identical version but different size.

Finished loading LogManager
System.TypeLoadException: Could not load type 'VRage.Common.Utils.MyFileSystem' from assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.Support.ApplicationLog..ctor(Boolean useGamePath)
   at SEModAPIInternal.Support.LogManager.get_APILog()
AppDomain.UnhandledException - System.Exception: Failed to create API log!
   at SEModAPIInternal.Support.LogManager.get_APILog()
   at SEServerExtender.Program.Start(String[] args)
   at SEServerExtender.Program.Main(String[] args)
System.TypeLoadException: Could not load type 'VRage.Common.Utils.MyFileSystem' from assembly 'VRage.Library, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at SEModAPIInternal.Support.ApplicationLog..ctor(Boolean useGamePath)
   at SEModAPIInternal.Support.LogManager.get_APILog()

Unhandled Exception: System.Exception: Failed to create API log!
   at SEModAPIInternal.Support.LogManager.get_APILog()
   at SEServerExtender.Program.Start(String[] args)
   at SEServerExtender.Program.Main(String[] args)
