### ISSUE TITLE
0.2.0 Crash Report

### ISSUE THREAD

**Issue by ShadoWallker** [SEModCommunity/SE-Community-Mod-API#46]
On startup this is what is produced. The server managed to stay up for about 10 minutes before crashing. Only the chat tab was used. 

---

SpaceEngineers-Dedicated.log 38MB in 5 minutes.

---

  Exception occured: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at 33FB6E717989660631E6772B99F502AD.DE48496EE9812E665B802D5FE9E7AD77.EFBD3CF8717682D7B59A5878FF97E0BB()
   at 6DDCED906C852CFDABA0B56B84D0BD74.F00C92FFA6F55CD283D86570FFC332AE.GetObjectBuilderCubeBlock()
   at 6DDCED906C852CFDABA0B56B84D0BD74.54A8BE425EAC4A11BFF922CFB5FF89D0.83286AEFA2A2AC71D1E54C9514B7D8C4(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   at 5BCAC68007431E61367F5B2CF24E2D6F.98262C3F38A1199E47F2B9338045794C.C1C9A52368857ABA8CC1E2FC18AEA92B(MyObjectBuilder_CubeGrid B55A0005A1AFE93B57C5CD3194BECA33, Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   at 5BCAC68007431E61367F5B2CF24E2D6F.98262C3F38A1199E47F2B9338045794C.GetObjectBuilder(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.BaseInternalWrapper.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters)
2014-07-02 14:32:56.898 - Thread:   1 ->  Inner Exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at 33FB6E717989660631E6772B99F502AD.DE48496EE9812E665B802D5FE9E7AD77.EFBD3CF8717682D7B59A5878FF97E0BB()
   at 6DDCED906C852CFDABA0B56B84D0BD74.F00C92FFA6F55CD283D86570FFC332AE.GetObjectBuilderCubeBlock()
   at 6DDCED906C852CFDABA0B56B84D0BD74.54A8BE425EAC4A11BFF922CFB5FF89D0.83286AEFA2A2AC71D1E54C9514B7D8C4(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   at 5BCAC68007431E61367F5B2CF24E2D6F.98262C3F38A1199E47F2B9338045794C.C1C9A52368857ABA8CC1E2FC18AEA92B(MyObjectBuilder_CubeGrid B55A0005A1AFE93B57C5CD3194BECA33, Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   at 5BCAC68007431E61367F5B2CF24E2D6F.98262C3F38A1199E47F2B9338045794C.GetObjectBuilder(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
2014-07-02 14:32:56.898 - Thread:   1 ->  System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseEntityManagerWrapper.GetAPIEntityList[T,TO](MyObjectBuilderTypeEnum type)
2014-07-02 14:33:20.964 - Thread:   1 ->  Exception occured: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at 33FB6E717989660631E6772B99F502AD.DE48496EE9812E665B802D5FE9E7AD77.EFBD3CF8717682D7B59A5878FF97E0BB()
   at 6DDCED906C852CFDABA0B56B84D0BD74.F00C92FFA6F55CD283D86570FFC332AE.GetObjectBuilderCubeBlock()
   at 6DDCED906C852CFDABA0B56B84D0BD74.54A8BE425EAC4A11BFF922CFB5FF89D0.83286AEFA2A2AC71D1E54C9514B7D8C4(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   at 5BCAC68007431E61367F5B2CF24E2D6F.98262C3F38A1199E47F2B9338045794C.C1C9A52368857ABA8CC1E2FC18AEA92B(MyObjectBuilder_CubeGrid B55A0005A1AFE93B57C5CD3194BECA33, Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   at 5BCAC68007431E61367F5B2CF24E2D6F.98262C3F38A1199E47F2B9338045794C.GetObjectBuilder(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.BaseInternalWrapper.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters)
2014-07-02 14:33:20.964 - Thread:   1 ->  Inner Exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at 33FB6E717989660631E6772B99F502AD.DE48496EE9812E665B802D5FE9E7AD77.EFBD3CF8717682D7B59A5878FF97E0BB()
   at 6DDCED906C852CFDABA0B56B84D0BD74.F00C92FFA6F55CD283D86570FFC332AE.GetObjectBuilderCubeBlock()
   at 6DDCED906C852CFDABA0B56B84D0BD74.54A8BE425EAC4A11BFF922CFB5FF89D0.83286AEFA2A2AC71D1E54C9514B7D8C4(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   at 5BCAC68007431E61367F5B2CF24E2D6F.98262C3F38A1199E47F2B9338045794C.C1C9A52368857ABA8CC1E2FC18AEA92B(MyObjectBuilder_CubeGrid B55A0005A1AFE93B57C5CD3194BECA33, Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   at 5BCAC68007431E61367F5B2CF24E2D6F.98262C3F38A1199E47F2B9338045794C.GetObjectBuilder(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
2014-07-02 14:33:20.964 - Thread:   1 ->  System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseEntityManagerWrapper.GetAPIEntityList[T,TO](MyObjectBuilderTypeEnum type)

---

After that, this over and over from the server log.

---

at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.BaseInternalWrapper.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters)
2014-07-02 14:36:47.739 - Thread:   1 ->  Inner Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at 5BCAC68007431E61367F5B2CF24E2D6F.F6DF01EE4159339113BB9650DEEE1913.GetObjectBuilder(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
2014-07-02 14:36:47.739 - Thread:   1 ->  System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseEntityManagerWrapper.GetAPIEntityList[T,TO](MyObjectBuilderTypeEnum type)
2014-07-02 14:36:47.739 - Thread:   1 ->  Exception occured: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at 5BCAC68007431E61367F5B2CF24E2D6F.F6DF01EE4159339113BB9650DEEE1913.GetObjectBuilder(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   --- End of inner exception stack trace ---

---

SEModAPIInternal.log 2MB

---

2014-07-02 14:36:47.615 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'

Roughly 1 or 2 of these errors every second.

**Comment by chessmaster42** [comment]
It's going to be hard to tell since we've cleaned up and reworked all of the code that this comes from. But I'm pretty sure that we've got this one fixed for the next release. In any case I do have some questions for you:

Do you use any modded blocks on your server?
Can you post the full logs to pastebin and put the links in a comment?
Does this happen every time you start it?
Does this only happen once players connect or just when running idle?
Can you post your world file for me to take a look at?

**Comment by chessmaster42** [comment]
Updated server tool is out now and this should be fixed by nature of all of the code cleanup we did. Can you please retest? Issue will be closed if there is no response within a few days.
