### ISSUE TITLE
getting frequent server crashes with 0.2.2.1

### ISSUE THREAD

**Issue by ghost** [SEModCommunity/SE-Community-Mod-API#54]
About 5 minutes after the server starts it will crash with the following log error:

2014-07-07 07:40:43.356 - Thread:   1 ->  Exception occured: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at 5BCAC68007431E61367F5B2CF24E2D6F.E5A0E3F04CC6DEFB7410825523C63704.GetObjectBuilder(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters)
2014-07-07 07:40:43.356 - Thread:   1 ->  Inner Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at 5BCAC68007431E61367F5B2CF24E2D6F.E5A0E3F04CC6DEFB7410825523C63704.GetObjectBuilder(Boolean A5DC70F106B952A1255F4B70E35F9DCD)
2014-07-07 07:40:43.356 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.SectorObjectManager.LoadDynamic()

**Comment by ghost** [comment]
Also see several repeating error in SEInternalMODAPI logfile:

2014-07-07 07:37:17.950 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:37:17.955 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:37:17.955 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:37:17.956 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:37:17.956 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:37:17.957 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:37:56.441 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:38:35.046 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:38:35.047 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:39:16.755 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:39:16.756 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:39:16.756 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:39:26.731 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'
2014-07-07 07:40:43.356 - Thread:   1 ->  Failed to invoke entity method 'GetObjectBuilder'

**Comment by chessmaster42** [comment]
This is specifically related to meteors and I'm working on a hotfix. Should be out later this morning if I can track down why the internal method there in the meteor is failing.

**Comment by ghost** [comment]
Sounds good, thanks.  I'm happy to help test anything if needed.

**Comment by chessmaster42** [comment]
Fixed in 0.2.3 release
