### ISSUE TITLE
Crash trying to start server 0.2.2.1

### ISSUE THREAD

**Issue by CaitlynMainer** [SEModCommunity/SE-Community-Mod-API#55]
SE Version: 01.037.014 x64
Crashlog: http://paste.pc-logix.com/view/raw/25231f7a
Screenshot: http://puu.sh/a444n/f3e1643391.jpg

I can start the server via the normal exe, but trying to start it via SEServerExtender produces the above results.  I have no plugins installed.

**Comment by CaitlynMainer** [comment]
Building from source results in

2014-07-09 17:32:52.143 - Thread:   1 ->  Exception occured: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.HashSet`1.Enumerator.MoveNext()
   at SEModAPIInternal.API.Utility.UtilityFunctions.ConvertEntityHashSet[T](IEnumerable`1 source)

**Comment by chessmaster42** [comment]
Fixed in 0.2.3 release
