### ISSUE TITLE
minor: plugin update being called after server is halted

### ISSUE THREAD

**Issue by DraygoKorvan** [SEModCommunity/SE-Community-Mod-API#64]
a plugin's update() is still continuously called when server is halted. Not sure if this is WAI.

**Comment by chessmaster42** [comment]
Can you pull down the latest from the repo and see if this is still occurring? It's supposed to stop the update timer/thread when the server stops.

**Comment by DraygoKorvan** [comment]
currently update isn't being called at all.

**Comment by chessmaster42** [comment]
I've been testing this myself and on another server and the main plugin update loop is being called just fine. Can you provide a log and some more details? Obviously something isn't right here but I can't produce the problem

**Comment by DraygoKorvan** [comment]
Found the exception being thrown, this wasn't being thrown before your update so not too sure what changed, ill do some work on my end though:

2014-07-15 17:06:42.352 - Thread:  10 ->  Exception occured: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.MissingMethodException: Method not found: 'Sandbox.Common.ObjectBuilders.VRageData.SerializableVector3 SEModAPIInternal.API.Entity.BaseEntity.get_Position()'.
   at PhysicsAsteroidsPlugin.Core.Update()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SEModAPIExtensions.API.PluginManager.Update()

**Comment by DraygoKorvan** [comment]
pastebin of the log:
http://pastebin.com/EhPJer8k
