### ISSUE TITLE
Server keeps crashing [0.2.5.4 Dev Build]

### ISSUE THREAD

**Issue by Universum01** [SEModCommunity/SE-Community-Mod-API#74]
Server just keeps shutting off, here is from the log report.

Idk if its an issue with the wrapper or the server.

```

2014-07-21 17:34:30.959 - Thread:   4 ->  Failed to invoke entity method 'GetObjectBuilder' on type '8AE833214C3909EE05128EF5DD9C9E5E.0BA7DA0950457C6BB5A4FAD34B2CA907': Exception has been thrown by the target of an invocation.
2014-07-21 17:34:31.063 - Thread:   4 ->  Failed to invoke entity method 'GetObjectBuilder' on type '8AE833214C3909EE05128EF5DD9C9E5E.0BA7DA0950457C6BB5A4FAD34B2CA907': Exception has been thrown by the target of an invocation.
2014-07-21 17:34:31.182 - Thread:   4 ->  Failed to invoke entity method 'GetObjectBuilder' on type '8AE833214C3909EE05128EF5DD9C9E5E.0BA7DA0950457C6BB5A4FAD34B2CA907': Exception has been thrown by the target of an invocation.
2014-07-21 17:34:31.289 - Thread:   4 ->  Failed to invoke entity method 'GetObjectBuilder' on type '8AE833214C3909EE05128EF5DD9C9E5E.0BA7DA0950457C6BB5A4FAD34B2CA907': Exception has been thrown by the target of an invocation.
2014-07-21 17:36:27.033 - Thread:   4 ->  TargetInvocationException - Server crashed
2014-07-21 17:36:27.034 - Thread:   4 ->  Exception occured: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Sandbox.Graphics.MyGuiManager.MeasureString(MyFontEnum font, StringBuilder text, Single scale)
   at Sandbox.Graphics.GUI.MyGuiScreenMessageBox.RecreateControls(Boolean constructor)
   at Sandbox.Graphics.GUI.MyGuiScreenMessageBox..ctor(MyMessageBoxStyleEnum styleEnum, MyMessageBoxButtonsType buttonType, StringBuilder messageText, StringBuilder messageCaption, MyTextsWrapperEnum okButtonText, MyTextsWrapperEnum cancelButtonText, MyTextsWrapperEnum yesButtonText, MyTextsWrapperEnum noButtonText, Action`1 callback, Int32 timeoutInMiliseconds, ResultEnum focusedResult)
   at 6D7C9F7F9CFF9877B430DBAFB54F1802.8DEBD6C63930F8C065956AC979F27488.858DA51EB20785A82D9A03614304088A.0187A29A24275EC024A192E7E235CC2E.407BBD9F80B3398EDCEBFDCBDBF48BA4()
   at ParallelTasks.Parallel.RunCallbacks()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.EC90B1C44E3C361983D093F355FF0CC8(Single D0A668B86020514B76C774AD3D4C5778)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.C3E0BD2869E26BB191C5193C7E9644DD()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.2457E95BE2F0D1F1A4A009B2B1DBBDA4()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.B3119CD657D221E30C363AF98704D851()
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.246E732EE67F7F6F88C4FF63B3901107()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.523C8831DA5DAB3A19F6D33A2C6437B5()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.26A7ABEA729FAE1F24679E21470F8E98(String 8BF03A34188889479CB413E58490FC37, String 48C45E39212AAA2B19C972DA9195F48A, Boolean 7AC487C1B445CD9F481CF5FE695A7CEA, Boolean 4292A7A4DACAF323E558B7E11DD3CF00)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SEModAPIInternal.API.Server.ServerAssemblyWrapper.StartServer(String worldName, String instanceName, Boolean useConsole)
2014-07-21 17:36:27.034 - Thread:   4 ->  Inner Exception: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Sandbox.Graphics.MyGuiManager.MeasureString(MyFontEnum font, StringBuilder text, Single scale)
   at Sandbox.Graphics.GUI.MyGuiScreenMessageBox.RecreateControls(Boolean constructor)
   at Sandbox.Graphics.GUI.MyGuiScreenMessageBox..ctor(MyMessageBoxStyleEnum styleEnum, MyMessageBoxButtonsType buttonType, StringBuilder messageText, StringBuilder messageCaption, MyTextsWrapperEnum okButtonText, MyTextsWrapperEnum cancelButtonText, MyTextsWrapperEnum yesButtonText, MyTextsWrapperEnum noButtonText, Action`1 callback, Int32 timeoutInMiliseconds, ResultEnum focusedResult)
   at 6D7C9F7F9CFF9877B430DBAFB54F1802.8DEBD6C63930F8C065956AC979F27488.858DA51EB20785A82D9A03614304088A.0187A29A24275EC024A192E7E235CC2E.407BBD9F80B3398EDCEBFDCBDBF48BA4()
   at ParallelTasks.Parallel.RunCallbacks()
   at AAC05F537A6F0F6775339593FBDFC564.D580AE7552E79DAB03A3D64B1F7B67F9.EC90B1C44E3C361983D093F355FF0CC8(Single D0A668B86020514B76C774AD3D4C5778)
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.C3E0BD2869E26BB191C5193C7E9644DD()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.2457E95BE2F0D1F1A4A009B2B1DBBDA4()
   at 168638249D29224100DB50BB468E7C07.7BAD4AFD06B91BCD63EA57F7C0D4F408.B3119CD657D221E30C363AF98704D851()
   at B337879D0C82A5F9C44D51D954769590.B3531963E948FB4FA1D057C4340C61B4.246E732EE67F7F6F88C4FF63B3901107()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.523C8831DA5DAB3A19F6D33A2C6437B5()
   at 83BCBFA49B3A2A6EC1BC99583DA2D399.49BCFF86BA276A9C7C0D269C2924DE2D.26A7ABEA729FAE1F24679E21470F8E98(String 8BF03A34188889479CB413E58490FC37, String 48C45E39212AAA2B19C972DA9195F48A, Boolean 7AC487C1B445CD9F481CF5FE695A7CEA, Boolean 4292A7A4DACAF323E558B7E11DD3CF00)
2014-07-21 17:36:27.035 - Thread:   4 ->     at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at SEModAPIInternal.API.Server.ServerAssemblyWrapper.StartServer(String worldName, String instanceName, Boolean useConsole)
   at SEServerExtender.Server.RunServer()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()


```

**Comment by DraygoKorvan** [comment]
Happens right as you hit start server?

**Comment by Universum01** [comment]
No, randomly when its running

**Comment by chessmaster42** [comment]
It was a bug with the vanilla auto-save. Because we've added our own save function into the tool you no longer need to have the buggy-as-hell default auto-save turned on. The tools save will go every 2 minutes and only takes about 2 seconds to save out with a large world (100+ asteroids, 20MB+ sector file). So to completely get rid of this error just turn off the default auto-save option in the checkpoint file (Sandbox.sbc).
