### ISSUE TITLE
init failures and method not found after 1041014

### ISSUE THREAD

**Issue by ghost** [SEModCommunity/SE-Community-Mod-API#88]
Entity list is empty after world loads.

Error log is spamming:
2014-08-01 09:57:30.041 - Thread:   1 ->  Exception occured: System.Exception: Method is empty
   at SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters)
2014-08-01 09:57:30.041 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseEntity.GetEntityId(Object entity)
2014-08-01 09:57:30.041 - Thread:   1 ->  Exception occured: System.Exception: Method not found
   at SEModAPIInternal.API.Entity.BaseObject.GetEntityMethod(Object gameEntity, String methodName)
2014-08-01 09:57:30.041 - Thread:   1 ->  Exception occured: System.Exception: Method is empty
   at SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters)
2014-08-01 09:57:30.041 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseEntity.GetEntityId(Object entity)
2014-08-01 09:57:30.041 - Thread:   1 ->  Exception occured: System.Exception: Method not found
   at SEModAPIInternal.API.Entity.BaseObject.GetEntityMethod(Object gameEntity, String methodName)
2014-08-01 09:57:30.041 - Thread:   1 ->  Exception occured: System.Exception: Method is empty
   at SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters)
2014-08-01 09:57:30.041 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseEntity.GetEntityId(Object entity)
2014-08-01 09:57:30.041 - Thread:   1 ->  Exception occured: System.Exception: Method not found
   at SEModAPIInternal.API.Entity.BaseObject.GetEntityMethod(Object gameEntity, String methodName)
2014-08-01 09:57:30.042 - Thread:   1 ->  Exception occured: System.Exception: Method is empty
   at SEModAPIInternal.API.Entity.BaseObject.InvokeEntityMethod(Object gameEntity, String methodName, Object[] parameters)
2014-08-01 09:57:30.042 - Thread:   1 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at SEModAPIInternal.API.Entity.BaseEntity.GetEntityId(Object entity)

API Internal is spamming: 
2014-08-01 09:57:30.084 - Thread:   1 ->  Failed to get entity method 'D524D6A5CA90978702080AE100BB664B': Method not found
2014-08-01 09:57:30.084 - Thread:   1 ->  Failed to invoke entity method 'D524D6A5CA90978702080AE100BB664B' on type '5BCAC68007431E61367F5B2CF24E2D6F.98262C3F38A1199E47F2B9338045794C': Method is empty
2014-08-01 09:57:30.084 - Thread:   1 ->  Failed to get entity method 'D524D6A5CA90978702080AE100BB664B': Method not found
2014-08-01 09:57:30.084 - Thread:   1 ->  Failed to invoke entity method 'D524D6A5CA90978702080AE100BB664B' on type '5BCAC68007431E61367F5B2CF24E2D6F.98262C3F38A1199E47F2B9338045794C': Method is empty
2014-08-01 09:57:30.084 - Thread:   1 ->  Failed to get entity method 'D524D6A5CA90978702080AE100BB664B': Method not found
2014-08-01 09:57:30.084 - Thread:   1 ->  Failed to invoke entity method 'D524D6A5CA90978702080AE100BB664B' on type '5BCAC68007431E61367F5B2CF24E2D6F.98262C3F38A1199E47F2B9338045794C': Method is empty
2014-08-01 09:57:30.085 - Thread:   1 ->  Failed to get entity method 'D524D6A5CA90978702080AE100BB664B': Method not found

**Comment by chessmaster42** [comment]
Hotfix is already out: https://github.com/SEModCommunity/SE-Community-Mod-API/releases/tag/v0.2.7.1-extender-alpha

**Comment by ghost** [comment]
you're fast, working fine now, thx!
