### ISSUE TITLE
User list becomes empty

### ISSUE THREAD

**Issue by Tyrsis** [SEModCommunity/SE-Community-Mod-API#91]
I currently have 20 users on the server, and the user list in the chat screen is empty.  It was working earlier, but now nothing is being added to the list.  Not sure what caused it either.

**Comment by chessmaster42** [comment]
This might be related to the enhancements to the player manager but there's nothing I can do without logs to reference. Can you please post your SEModAPIInternal.log and SpaceEngineersDedicated.log to pastebin.com and put the links here? Do NOT paste the log content into a comment.

Also, are the chat messages still showing up and do they show the right name?

**Comment by Tyrsis** [comment]
http://pastebin.com/hCqiYunf

**Comment by Tyrsis** [comment]
And yes, chat messages are still showing up.  Chat is still working fine, the user list is just blank.  (user names are showing up properly in the chat window though with what they are saying in there)

**Comment by DraygoKorvan** [comment]
Minor point, I see the MotD plugin is being initialized twice at the start of your log, if there is only one dll for the motd plugin in the Mods folder create a new issue on it. If there is a second folder, delete the folder containing the oldest version. This has nothing to do with the Chat bug (well it should have nothing to do with it).

**Comment by Tyrsis** [comment]
Happened again, but this looks like the cause:

2014-08-02 08:20:31.789 - Thread:   1 ->  Disposing CharacterEntity '72226888348617882'
2014-08-02 08:20:38.799 - Thread:   1 ->  Disposing CharacterEntity '72081779048007949'
2014-08-02 08:20:44.324 - Thread:   1 ->  Application.ThreadException
2014-08-02 08:20:44.324 - Thread:   1 ->  Exception occured: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at SEServerExtender.SEServerExtender.ChatViewRefresh(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
2014-08-02 08:20:44.789 - Thread:   1 ->  Disposing CharacterEntity '72081779048007949'
2014-08-02 08:21:22.789 - Thread:   1 ->  Disposing CharacterEntity '72226888348617882'

**Comment by chessmaster42** [comment]
Thanks for the extra info! The problem was located and I think I have it fixed. It will be in the next dev build.
