### ISSUE TITLE
0.2.7.3 recurring error

### ISSUE THREAD

**Issue by ghost** [SEModCommunity/SE-Community-Mod-API#92]
Seeing recurring error on player joins and disconnects:

2014-08-02 15:47:09.080 - Thread:   4 ->  Next activation in 00:00:10
2014-08-02 15:47:12.084 - Thread:   4 ->  User left Memory Alpha
2014-08-02 15:47:12.095 - Thread:   4 ->  SetPlayerCharacter called
2014-08-02 15:47:12.126 - Thread:   6 ->  Exception occured: System.ArgumentException: Object of type 'SEModAPIInternal.API.Entity.BaseEntity' cannot be converted to type 'SEModAPIInternal.API.Entity.Sector.SectorObject.CharacterEntity'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SEModAPIExtensions.API.PluginManager.Update()
2014-08-02 15:47:19.742 - Thread:   4 ->  MyGlobalEvent.RecalculateActivationTime:
2014-08-02 15:47:19.742 - Thread:   4 ->  Next activation in 00:00:10
2014-08-02 15:47:30.807 - Thread:   4 ->  GC Memory: 1,327,874,200 B
2014-08-02 15:47:31.404 - Thread:   4 ->  MyGlobalEvent.RecalculateActivationTime:
2014-08-02 15:47:31.404 - Thread:   4 ->  Next activation in 00:00:10
2014-08-02 15:47:41.470 - Thread:   4 ->  MyGlobalEvent.RecalculateActivationTime:
2014-08-02 15:47:41.470 - Thread:   4 ->  Next activation in 00:00:10
2014-08-02 15:47:44.565 - Thread:   4 ->  Peer2Peer_SessionRequest 76561197987254130
2014-08-02 15:47:45.524 - Thread:   4 ->  OnConnectedPlayer Memory Alpha attempt
2014-08-02 15:47:45.972 - Thread:   4 ->  Server ValidateAuthTicketResponse (k_EAuthSessionResponseOK), owner: 76561197987254130
2014-08-02 15:47:46.119 - Thread:   4 ->  World request received: Memory Alpha
2014-08-02 15:47:46.120 - Thread:   4 ->  ...responding
2014-08-02 15:47:46.140 - Thread:   6 ->  Exception occured: System.ArgumentException: Object of type 'SEModAPIInternal.API.Entity.BaseEntity' cannot be converted to type 'SEModAPIInternal.API.Entity.Sector.SectorObject.CharacterEntity'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at SEModAPIExtensions.API.PluginManager.Update()

**Comment by chessmaster42** [comment]
This is currently being fixed but we haven't released a dev build with it yet. Thanks for reporting this!
